-- AsisControl: base comercial multi-tenant
-- Ejecutar SOLO en la nueva base de datos, después de restaurar el respaldo base.
-- No ejecutar en la base que hoy está en producción.
-- Esta migración agrega el modelo comercial; el backend debe actualizarse antes
-- de obligar team_id como NOT NULL o habilitar políticas RLS.

BEGIN;

-- ============================================================
-- 1. Equipos, membresías y alcance académico
-- ============================================================

CREATE TABLE IF NOT EXISTS public.teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_cuenta varchar(10) NOT NULL,
  nombre varchar(200) NOT NULL,
  nombre_escuela varchar(200),
  propietario_usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  email_contacto varchar(150),
  telefono varchar(30),
  direccion text,
  ciudad varchar(100),
  estado varchar(100),
  pais varchar(100) NOT NULL DEFAULT 'México',
  codigo_postal varchar(12),
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT teams_tipo_cuenta_check CHECK (tipo_cuenta IN ('personal', 'team')),
  CONSTRAINT teams_nombre_escuela_team_check CHECK (
    tipo_cuenta = 'personal' OR nombre_escuela IS NOT NULL
  )
);

-- Una cuenta Personal pertenece a una sola persona. El mismo usuario puede ser
-- director de uno o más teams empresariales si en el futuro se requiere.
CREATE UNIQUE INDEX IF NOT EXISTS teams_propietario_personal_unico
  ON public.teams (propietario_usuario_id)
  WHERE tipo_cuenta = 'personal';

CREATE TABLE IF NOT EXISTS public.team_miembros (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  rol varchar(20) NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  invitado_por_usuario_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  joined_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT team_miembros_rol_check CHECK (rol IN ('director', 'subdirector', 'maestro')),
  CONSTRAINT team_miembros_team_usuario_unico UNIQUE (team_id, usuario_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS team_un_director_activo
  ON public.team_miembros (team_id)
  WHERE rol = 'director' AND activo;

-- El catálogo existente niveles_educativos sigue siendo global. Esta tabla indica
-- qué niveles ofrece cada escuela y permite configurarlos por team.
CREATE TABLE IF NOT EXISTS public.team_niveles_educativos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  nivel_educativo_id integer NOT NULL REFERENCES public.niveles_educativos(id) ON DELETE RESTRICT,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT team_niveles_educativos_unico UNIQUE (team_id, nivel_educativo_id)
);

-- Director ve todo su team sin filas aquí. Subdirector y maestro requieren una o
-- más filas para poder operar o consultar esos niveles.
CREATE TABLE IF NOT EXISTS public.team_miembro_niveles (
  team_miembro_id bigint NOT NULL REFERENCES public.team_miembros(id) ON DELETE CASCADE,
  team_nivel_educativo_id bigint NOT NULL REFERENCES public.team_niveles_educativos(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (team_miembro_id, team_nivel_educativo_id)
);

CREATE TABLE IF NOT EXISTS public.invitaciones_team (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  codigo varchar(64) NOT NULL UNIQUE,
  rol varchar(20) NOT NULL,
  creado_por_usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  email_destino varchar(150),
  max_usos integer NOT NULL DEFAULT 1 CHECK (max_usos > 0),
  usos integer NOT NULL DEFAULT 0 CHECK (usos >= 0),
  expira_at timestamptz,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invitaciones_team_rol_check CHECK (rol IN ('subdirector', 'maestro')),
  CONSTRAINT invitaciones_team_usos_check CHECK (usos <= max_usos)
);

CREATE TABLE IF NOT EXISTS public.invitacion_team_niveles (
  invitacion_id bigint NOT NULL REFERENCES public.invitaciones_team(id) ON DELETE CASCADE,
  team_nivel_educativo_id bigint NOT NULL REFERENCES public.team_niveles_educativos(id) ON DELETE CASCADE,
  PRIMARY KEY (invitacion_id, team_nivel_educativo_id)
);

-- ============================================================
-- 2. Suscripciones, prueba, pagos por transferencia y términos
-- ============================================================

CREATE TABLE IF NOT EXISTS public.planes (
  codigo varchar(30) PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  tipo_cuenta varchar(10) NOT NULL,
  precio_mensual numeric(10,2) NOT NULL CHECK (precio_mensual >= 0),
  max_alumnos integer,
  max_grupos integer,
  permite_qr boolean NOT NULL DEFAULT false,
  permite_exportar_concentrado boolean NOT NULL DEFAULT false,
  caracteristicas jsonb NOT NULL DEFAULT '{}'::jsonb,
  activo boolean NOT NULL DEFAULT true,
  CONSTRAINT planes_tipo_cuenta_check CHECK (tipo_cuenta IN ('personal', 'team')),
  CONSTRAINT planes_limites_check CHECK (
    (max_alumnos IS NULL OR max_alumnos > 0) AND
    (max_grupos IS NULL OR max_grupos > 0)
  )
);

INSERT INTO public.planes (
  codigo, nombre, tipo_cuenta, precio_mensual, max_alumnos, max_grupos,
  permite_qr, permite_exportar_concentrado, caracteristicas
) VALUES
  ('PERSONAL_PLATA', 'Personal Plata', 'personal', 150.00, 45, 3, false, false,
   '{"reportes": true, "asistencia_manual": true}'),
  ('PERSONAL_ORO', 'Personal Oro', 'personal', 250.00, NULL, NULL, true, true,
   '{"reportes": true, "asistencia_manual": true}'),
  ('TEAM', 'Team', 'team', 1000.00, NULL, NULL, true, true,
   '{"reportes": true, "asistencia_manual": true}')
ON CONFLICT (codigo) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  precio_mensual = EXCLUDED.precio_mensual,
  max_alumnos = EXCLUDED.max_alumnos,
  max_grupos = EXCLUDED.max_grupos,
  permite_qr = EXCLUDED.permite_qr,
  permite_exportar_concentrado = EXCLUDED.permite_exportar_concentrado,
  caracteristicas = EXCLUDED.caracteristicas;

CREATE TABLE IF NOT EXISTS public.suscripciones_team (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  plan_codigo varchar(30) NOT NULL REFERENCES public.planes(codigo),
  estado varchar(20) NOT NULL,
  inicio_prueba_at timestamptz,
  fin_prueba_at timestamptz,
  inicio_periodo_at timestamptz,
  fin_periodo_at timestamptz,
  tolerancia_hasta_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT suscripciones_team_estado_check CHECK (
    estado IN ('prueba', 'pendiente_pago', 'activa', 'tolerancia', 'suspendida', 'cancelada')
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS suscripcion_team_actual_unica
  ON public.suscripciones_team (team_id)
  WHERE estado IN ('prueba', 'pendiente_pago', 'activa', 'tolerancia');

CREATE TABLE IF NOT EXISTS public.pagos_transferencia (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suscripcion_id bigint NOT NULL REFERENCES public.suscripciones_team(id) ON DELETE RESTRICT,
  monto numeric(10,2) NOT NULL CHECK (monto > 0),
  moneda char(3) NOT NULL DEFAULT 'MXN',
  referencia varchar(150),
  comprobante_url text NOT NULL,
  fecha_transferencia date,
  estado varchar(20) NOT NULL DEFAULT 'pendiente',
  enviado_por_usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  revisado_por_usuario_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  revisado_at timestamptz,
  nota_revision text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pagos_transferencia_estado_check CHECK (estado IN ('pendiente', 'aprobado', 'rechazado'))
);

CREATE TABLE IF NOT EXISTS public.aceptaciones_terminos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  version_terminos varchar(50) NOT NULL,
  aceptado_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip inet,
  user_agent text,
  CONSTRAINT aceptaciones_terminos_unico UNIQUE (usuario_id, version_terminos)
);

-- ============================================================
-- 3. Pertenencia de los datos académicos al team
-- ============================================================

ALTER TABLE public.ciclos_escolares ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.niveles_academicos ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.materias ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.grupos ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.alumnos ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.configuraciones_evaluacion ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.etiquetas ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.tareas ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.calificaciones ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.grupo_materias ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.alumno_grupos ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.asistencia_sesiones ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.asistencia_registros ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;
ALTER TABLE public.alumno_qr_tokens ADD COLUMN IF NOT EXISTS team_id bigint
  REFERENCES public.teams(id) ON DELETE CASCADE;

-- Un grupo ya no pertenece a un maestro. Los maestros se asignan mediante
-- grupo_materias, permitiendo un solo "1° A" con muchas materias y docentes.
ALTER TABLE public.grupos ALTER COLUMN maestro_id DROP NOT NULL;
ALTER TABLE public.materias ALTER COLUMN maestro_id DROP NOT NULL;
ALTER TABLE public.grupos DROP CONSTRAINT IF EXISTS grupos_nivel_academico_ciclo_maestro_nombre_key;
CREATE UNIQUE INDEX IF NOT EXISTS grupos_team_nivel_ciclo_nombre_unico
  ON public.grupos (team_id, nivel_academico_id, ciclo_escolar_id, nombre)
  WHERE team_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS materias_team_nombre_unico
  ON public.materias (team_id, lower(nombre))
  WHERE team_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS alumnos_team_matricula_unica
  ON public.alumnos (team_id, matricula)
  WHERE team_id IS NOT NULL AND matricula IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_team_miembros_usuario ON public.team_miembros (usuario_id, activo);
CREATE INDEX IF NOT EXISTS idx_team_miembro_niveles_miembro ON public.team_miembro_niveles (team_miembro_id);
CREATE INDEX IF NOT EXISTS idx_invitaciones_team_codigo ON public.invitaciones_team (codigo) WHERE activo;
CREATE INDEX IF NOT EXISTS idx_suscripciones_team_estado ON public.suscripciones_team (team_id, estado);
CREATE INDEX IF NOT EXISTS idx_pagos_transferencia_estado ON public.pagos_transferencia (estado, created_at);
CREATE INDEX IF NOT EXISTS idx_grupos_team ON public.grupos (team_id);
CREATE INDEX IF NOT EXISTS idx_alumnos_team ON public.alumnos (team_id);
CREATE INDEX IF NOT EXISTS idx_grupo_materias_team ON public.grupo_materias (team_id);
CREATE INDEX IF NOT EXISTS idx_asistencia_sesiones_team ON public.asistencia_sesiones (team_id);

COMMIT;

-- PASO POSTERIOR OBLIGATORIO (NO ejecutar hasta actualizar el backend):
-- 1. Cada INSERT debe enviar team_id.
-- 2. Validar el team del JWT/membresía en cada endpoint y función SQL.
-- 3. Poblar team_id si se migra información histórica.
-- 4. Solo entonces cambiar las columnas team_id a NOT NULL y activar RLS.
